apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pv-claim
  namespace: homework
spec:
  storageClassName: homework-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi